# Generated by Django 5.1.4 on 2024-12-16 15:30

import comments.services
import comments.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(2048)])),
                ('image', models.ImageField(blank=True, null=True, upload_to=comments.services.FileUploader('comments/images/%Y/%m/%d/'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'gif']), comments.validators.FileSizeValidator(300, 'kb'), comments.validators.ImageSizeValidator(320, 240)])),
                ('file', models.FileField(blank=True, null=True, upload_to=comments.services.FileUploader('comments/files/%Y/%m/%d/'), validators=[django.core.validators.FileExtensionValidator(['txt']), comments.validators.FileSizeValidator(100, 'kb')])),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
    ]
