# Generated by Django 5.1.4 on 2024-12-23 11:05

import comments.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2048), comments.validators.HTMLTagValidator(['p', 'strong', 'em', 'u', 's', 'code', 'a'], ['br'])]),
        ),
    ]
